# site settings
pagesDir: ./pages # .md files here
themeDir: ./themes/light
destinationDir: ./dist
dateTimeFormat: DD.MM.YYYY
rootFileName: index
debug: true

# static server
serverEnable: true
serverPort: 9090

# common data for site
context:
  title: RedSpirit Blog
  description: My simple texts